CREATE TABLE IF NOT EXISTS mainmenu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title VARCHAR NOT NULL,
url VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS logins(
login VARCHAR,
email VARCHAR,
password VARCHAR
);

CREATE TABLE IF NOT EXISTS posts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title VARCHAR NOT NULL,
price INTEGER NOT NULL,
text VARCHAR NOT NULL,
contact VARCHAR NOT NULL,
tm INTEGER NOT NULL
)